
project_id = "nsryemtjsudzbhoufcbl"

[functions.test-riot-api]
  verify_jwt = true

[functions.set-api-configuration]
  verify_jwt = true

[functions.get-api-configuration]
  verify_jwt = true

[functions.receive-game-stats]
  verify_jwt = false # We use custom token authentication
