
// This file is automatically generated by Supabase, but has been modified by Lovable.
// Lovable note: Updated to use environment variables for template compatibility.
// Environment variables will be used for local development and production deployment.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Retrieve Supabase URL and Anon Key from environment variables
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

// Check if the environment variables are set
if (!SUPABASE_URL) {
  console.error("Error: VITE_SUPABASE_URL is not set. Please ensure this environment variable is configured.");
  throw new Error("VITE_SUPABASE_URL is not set. Please check your .env file or deployment environment variables.");
}
if (!SUPABASE_ANON_KEY) {
  console.error("Error: VITE_SUPABASE_ANON_KEY is not set. Please ensure this environment variable is configured.");
  throw new Error("VITE_SUPABASE_ANON_KEY is not set. Please check your .env file or deployment environment variables.");
}

// The console error for missing environment variables will now appear
// if these are not set in the user's environment.

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL!, SUPABASE_ANON_KEY!, {
  auth: {
    storage: typeof window !== 'undefined' ? window.localStorage : undefined, // Use window.localStorage for browser
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true, // Default is true, good to be explicit
    flowType: 'implicit', // Use implicit flow for more reliable session handling
  },
});

